---
version: "3.8"
services:
  go:
    build:
      context: .
      target: godev
    init: true
    command: ["sleep", "infinity"]
    volumes:
      - ".:/src"
      - "go_cache:/root/.cache"
      - "go_pkg:/go/pkg"
volumes:
  go_cache:
  go_pkg:
